### ISSUE TITLE
Perhaps make these enums

### ISSUE THREAD

**Issue by arthurbernierjr** [hlysllrs/unit-2-project#1]
https://github.com/hlysllrs/unit-2-project/blob/63b1fb09e55f4b42ddc3d4588a341ee26a84ea7e/models/teamRole.js#L5

Since you already know what the roles can be, this will stop you from accidentally spelling something wrong etc,

```js
{
  thing: { type: String, required: true, enum: [ 'choice1', 'choice2']}
}
```

This applies to anything where you know you only want to accept a finite number of acceptable strings.

**Comment by arthurbernierjr** [comment]
https://github.com/hlysllrs/unit-2-project/blob/63b1fb09e55f4b42ddc3d4588a341ee26a84ea7e/models/projectRole.js#L5

same

**Comment by hlysllrs** [comment]
Amazing! This is exactly what I wanted to do, I just didn't know how yet
